# Generated by Django 6.0.7 on 2026-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
