# Generated by Django 6.0.7 on 2026-09-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.event')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='booking.seat'),
        ),
    ]
