# Generated by Django 6.0.7 on 2026-09-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_seat_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
