# Generated by Django 6.0.7 on 2026-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_event_admin_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
