# Generated by Django 6.0.7 on 2026-10-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_code',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_used',
            field=models.BooleanField(default=False),
        ),
    ]
