# Generated by Django 6.0.7 on 2026-10-06 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_ticket_code_booking_ticket_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
